#!/bin/bash
set -e

read -e -p "Path to dotfiles folder: " dotfolder
dotfolder="${dotfolder/#\~/$HOME}"

link_dot() {
    local src="$1" dest="$2"
    if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
        echo "already linked: $dest -> $src"
    else
        ln -sf "$src" "$dest"
        echo "linked: $dest -> $src"
    fi
}

link_dot "$dotfolder/dotzshrc" ~/.zshrc
link_dot "$dotfolder/dottmux.conf" ~/.tmux.conf
link_dot "$dotfolder/dotgitignore.conf" ~/.gitignore
link_dot "$dotfolder/dotgitconfig" ~/.gitconfig
link_dot "$dotfolder/dotgitattribute" ~/.gitattribute
