#!/usr/bin/env python
# -.- coding: utf-8 -.-

import os, json
import subprocess
import sys


CONFIG_FILE = '.mg_storage_conf'

def main(src, dest):

    config = {}
    config_file = os.path.join(os.getenv("HOME"), CONFIG_FILE)
    
    with open(config_file) as f:
        config = json.load(f)

    cmd = config['cmd_pattern'].format(src.decode('utf-8'),
                                       dest.decode('utf-8'))
    # .開頭, path_to/.foo, Thumbs.db
    #\..*|.+\/\..+|.+/Thumbs.db

    print '[mg-storage] run: %s' % cmd

    # call cmd
    subprocess.call(cmd.split(' '))


if __name__ == '__main__':

    usage = "usage: mg-storage src dest"

    if len(sys.argv) > 2:
        main(sys.argv[1], sys.argv[2])
    else:
        print usage
