#! /usr/bin/env python

#
# my grep, v0.1
# 2008-12-30

import sys, os

exclude_files = ("TAGS", "tags")
command = "grep -HnrI --color"
for fname in exclude_files:
  command += " --exclude=" + fname

command += " " + sys.argv[1] + " *" 

os.system(command)
print command

